default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1071
  pool: 5

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  primary: &primary_production
    <<: *default
    database: api_production
    username: postgres
    password: 1071
  cache:
    <<: *primary_production
    database: api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: api_production_cable
    migrations_paths: db/cable_migrate
